# -*- coding: utf-8 -*-
"""streamlit_app2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZyrP3vpBalZJEhE49yu-mHf8RB8q6Dpo
"""

def train_model_with_validation(df, test_size=0.2):
    """
    Train SVM model using proper train-test split and cross-validation.
    This function ensures that reported accuracy reflects generalization performance.
    """
    try:
        # Map column names (handling your specific naming convention)
        df_renamed = df.copy()

        # Map power columns
        if 'opponent_1_estimated_punch_power' in df.columns:
            df_renamed['opponent_1_power'] = df['opponent_1_estimated_punch_power']
        if 'opponent_2_estimated_punch_power' in df.columns:
            df_renamed['opponent_2_power'] = df['opponent_2_estimated_punch_power']

        # Map resistance columns
        if 'opponent_1_estimated_punch_resistance' in df.columns:
            df_renamed['opponent_1_resistance'] = df['opponent_1_estimated_punch_resistance']
        if 'opponent_2_estimated_punch_resistance' in df.columns:
            df_renamed['opponent_2_resistance'] = df['opponent_2_estimated_punch_resistance']

        # Map ability columns
        if 'opponent_1_ability_to_take_punch' in df.columns:
            df_renamed['opponent_1_ability_to_take_punch'] = df['opponent_1_ability_to_take_punch']
        if 'opponent_2_ability_to_take_punch' in df.columns:
            df_renamed['opponent_2_ability_to_take_punch'] = df['opponent_2_ability_to_take_punch']

        # Map fighter names
        if 'opponent_1.x' in df.columns:
            df_renamed['opponent_1'] = df['opponent_1.x']
        if 'opponent_2.x' in df.columns:
            df_renamed['opponent_2'] = df['opponent_2.x']

        # Map fight_id
        if 'fight_id' in df.columns:
            df_renamed['fight_id'] = df['fight_id']

        # Check if we need to aggregate round-level data
        if 'round.x' in df_renamed.columns and df_renamed['round.x'].nunique() > 1:
            fight_data = df_renamed.groupby('fight_id').agg({
                'opponent_1': 'first',
                'opponent_2': 'first',
                'opponent_1_power': 'mean',
                'opponent_2_power': 'mean',
                'opponent_1_resistance': 'mean',
                'opponent_2_resistance': 'mean',
                'opponent_1_ability_to_take_punch': 'mean',
                'opponent_2_ability_to_take_punch': 'mean',
                'verdict': 'first'
            }).reset_index()
        else:
            fight_data = df_renamed.copy()

        # Calculate differences
        fight_data['power_diff'] = fight_data['opponent_1_power'] - fight_data['opponent_2_power']
        fight_data['resistance_diff'] = fight_data['opponent_1_resistance'] - fight_data['opponent_2_resistance']
        fight_data['ability_diff'] = fight_data['opponent_1_ability_to_take_punch'] - fight_data['opponent_2_ability_to_take_punch']

        # Extract verdict type
        def extract_verdict_type(verdict):
            if pd.isna(verdict):
                return None
            verdict_str = str(verdict).upper()
            if 'KO' in verdict_str:
                return 'KO'
            elif 'TKO' in verdict_str:
                return 'TKO'
            elif 'UD' in verdict_str:
                return 'UD'
            elif 'SD' in verdict_str:
                return 'SD'
            elif 'MD' in verdict_str:
                return 'MD'
            elif 'RTD' in verdict_str:
                return 'RTD'
            return None

        fight_data['verdict_type'] = fight_data['verdict'].apply(extract_verdict_type)
        fight_data = fight_data.dropna(subset=['verdict_type'])

        if len(fight_data) == 0:
            return None, None, None, None, None, None, None, None, None, None, None, "No valid verdict types found"

        # Prepare features and target
        features = ['power_diff', 'resistance_diff', 'ability_diff']
        X = fight_data[features].values  # Convert to numpy array with .values
        y = fight_data['verdict_type'].values  # Convert to numpy array with .values

        # Optional: Convert to float32 for better performance
        X = X.astype(np.float32)

        # ============================================
        # STEP 1: Train-Test Split (80-20 by default)
        # ============================================
        # Now X and y are numpy arrays, which work correctly with train_test_split
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=test_size, random_state=42, stratify=y
        )

        # ============================================
        # STEP 2: Standardize features using ONLY training data
        # ============================================
        scaler = StandardScaler()
        X_train_scaled = scaler.fit_transform(X_train)
        X_test_scaled = scaler.transform(X_test)  # Uses training mean/std

        # ============================================
        # STEP 3: Train SVM on training data only
        # ============================================
        model = SVC(kernel='rbf', C=10, gamma='scale', probability=True, random_state=123)
        model.fit(X_train_scaled, y_train)

        # ============================================
        # STEP 4: Evaluate on training data (for diagnostic reference only)
        # ============================================
        train_predictions = model.predict(X_train_scaled)
        train_accuracy = accuracy_score(y_train, train_predictions)

        # ============================================
        # STEP 5: Evaluate on test data (TRUE generalization performance)
        # ============================================
        test_predictions = model.predict(X_test_scaled)
        test_accuracy = accuracy_score(y_test, test_predictions)

        # ============================================
        # STEP 6: Cross-validation for robust estimate
        # ============================================
        # Use all data for cross-validation (with stratified folds)
        X_full_scaled = scaler.transform(X)  # Using already-fitted scaler
        cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

        # We need to fit a new model for each fold, so we'll use cross_val_score with the full pipeline
        from sklearn.pipeline import make_pipeline
        pipeline = make_pipeline(StandardScaler(), SVC(kernel='rbf', C=10, gamma='scale', random_state=123))
        cv_scores = cross_val_score(pipeline, X, y, cv=cv, scoring='accuracy')
        cv_mean = cv_scores.mean()
        cv_std = cv_scores.std()

        # ============================================
        # STEP 7: Retrain on FULL data for deployment
        # ============================================
        # After validation, retrain on all data for the prediction interface
        X_full_scaled_final = scaler.transform(X)  # Reuse scaling
        model.fit(X_full_scaled_final, y)

        # Final predictions on full set (for visualization only)
        final_predictions = model.predict(X_full_scaled_final)

        # Create results dataframe for display
        results_df = fight_data[['fight_id', 'opponent_1', 'opponent_2', 'verdict_type']].copy()
        results_df.columns = ['fight_id', 'opponent_1', 'opponent_2', 'actual_verdict']
        results_df['svm_prediction'] = final_predictions
        results_df['agreement'] = results_df['actual_verdict'] == results_df['svm_prediction']

        # Confusion matrix (on full data for visualization)
        cm = confusion_matrix(y, final_predictions)
        fig_cm = px.imshow(
            cm,
            x=model.classes_,
            y=model.classes_,
            text_auto=True,
            title="Confusion Matrix - SVM Predictions vs Actual",
            labels=dict(x="Predicted", y="Actual"),
            color_continuous_scale='Blues'
        )
        fig_cm.update_layout(height=500)

        # PCA visualization
        pca = PCA(n_components=2)
        pca_result = pca.fit_transform(X_full_scaled_final)
        pca_df = pd.DataFrame(pca_result, columns=['PC1', 'PC2'])
        pca_df['verdict'] = y

        color_map = {
            'KO': '#2E8B57', 'TKO': '#4169E1', 'UD': '#DC143C',
            'SD': '#FF8C00', 'MD': '#9370DB', 'RTD': '#FF69B4'
        }

        fig_pca = px.scatter(
            pca_df, x='PC1', y='PC2', color='verdict',
            title="PCA Visualization of Fight Data",
            labels={'PC1': f'PC1 ({pca.explained_variance_ratio_[0]:.1%})',
                   'PC2': f'PC2 ({pca.explained_variance_ratio_[1]:.1%})'},
            color_discrete_map=color_map
        )
        fig_pca.update_layout(height=500)

        # Feature distributions
        feature_data = fight_data[['verdict_type', 'power_diff', 'resistance_diff', 'ability_diff']]
        feature_melted = feature_data.melt(id_vars=['verdict_type'], var_name='Feature', value_name='Difference')

        fig_box = px.box(
            feature_melted,
            x='verdict_type',
            y='Difference',
            color='verdict_type',
            facet_col='Feature',
            title="Feature Distributions by Verdict Type"
        )
        fig_box.update_layout(height=500)

        # Prepare comprehensive status message
        status = f"""### ✅ MODEL TRAINING COMPLETE - VALIDATION RESULTS

**📊 Data Split Information:**
- Total fights: {len(fight_data)}
- Training set: {len(X_train)} fights ({test_size*100:.0f}% of data held out)
- Test set: {len(X_test)} fights ({test_size*100:.0f}% held out for final evaluation)

**🎯 Validation Metrics (True Generalization):**
- **5-Fold Cross-Validation Accuracy:** {cv_mean:.1%} +/- {cv_std:.1%}
- **Held-Out Test Accuracy:** {test_accuracy:.1%} (on {len(X_test)} unseen fights)
- **Training Accuracy (reference only):** {train_accuracy:.1%}

**⚠️ Interpretation:**
- Generalization gap: {train_accuracy - test_accuracy:.1%} difference between training and test
"""

        # Add interpretation based on generalization gap
        gap = train_accuracy - test_accuracy
        if gap < 0.05:
            status += "- ✅ Small generalization gap - model generalizes well to new data"
        elif gap < 0.10:
            status += "- ⚠️ Moderate generalization gap - some overfitting present"
        else:
            status += "- ❌ Large generalization gap - model may be overfitting"

        if cv_std > 0.08:
            status += "\n- ⚠️ High cross-validation variance - model performance depends on which fights are in the training set"

        # Add class distribution info
        class_counts = pd.Series(y).value_counts()
        status += f"\n\n**📈 Class Distribution:**\n"
        for verdict, count in class_counts.items():
            status += f"- {verdict}: {count} fights ({count/len(y)*100:.1f}%)\n"

        status += f"""

**📊 Model Complexity:**
- Classes: {', '.join(model.classes_)}
- Support Vectors: {len(model.support_)} out of {len(X_train)} training examples

**🔮 Practical Guidance:**
- The test accuracy of {test_accuracy:.1%} is the TRUE expected performance on new fights
- Use the prediction interface with this expectation in mind
- Predictions for majority classes (KO, UD) are more reliable than for rare classes
"""

        return (model, scaler, fight_data, results_df, fig_cm, fig_pca, fig_box,
                test_accuracy, cv_mean, cv_std, train_accuracy, status)

    except Exception as e:
        import traceback
        return None, None, None, None, None, None, None, None, None, None, None, f"❌ Error: {str(e)}\n\n{traceback.format_exc()}"