# -*- coding: utf-8 -*-
"""streamlit_app2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZyrP3vpBalZJEhE49yu-mHf8RB8q6Dpo
"""

# -*- coding: utf-8 -*-
"""Complete Boxing SVM Verdict Predictor - Streamlit App"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.pipeline import make_pipeline
import plotly.express as px
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import seaborn as sns

# Page configuration - MUST be the first Streamlit command
st.set_page_config(
    page_title="Boxing SVM Verdict Predictor",
    page_icon="🥊",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for better styling
st.markdown("""
<style>
    .stButton > button {
        background-color: #ff4b4b;
        color: white;
        font-weight: bold;
        width: 100%;
    }
    .stButton > button:hover {
        background-color: #ff6b6b;
    }
    .verdict-ko { color: #2E8B57; font-weight: bold; }
    .verdict-ud { color: #DC143C; font-weight: bold; }
    .verdict-sd { color: #FF8C00; font-weight: bold; }
    .verdict-md { color: #9370DB; font-weight: bold; }
    .verdict-rtd { color: #FF69B4; font-weight: bold; }
</style>
""", unsafe_allow_html=True)

# Initialize session state
if 'model' not in st.session_state:
    st.session_state.model = None
if 'scaler' not in st.session_state:
    st.session_state.scaler = None
if 'fight_data' not in st.session_state:
    st.session_state.fight_data = None
if 'trained' not in st.session_state:
    st.session_state.trained = False
if 'test_accuracy' not in st.session_state:
    st.session_state.test_accuracy = None

# Title
st.title("🥊 Boxing Audit Tool — SVM Verdict Classification")
st.markdown("### Support Vector Machine for Boxing Outcome Prediction")

# ============================================================================
# TRAIN MODEL FUNCTION (with proper validation)
# ============================================================================

def train_model_with_validation(df, test_size=0.2):
    """
    Train SVM model using proper train-test split and cross-validation.
    """
    try:
        df_renamed = df.copy()

        # Map column names
        if 'opponent_1_estimated_punch_power' in df.columns:
            df_renamed['opponent_1_power'] = df['opponent_1_estimated_punch_power']
        if 'opponent_2_estimated_punch_power' in df.columns:
            df_renamed['opponent_2_power'] = df['opponent_2_estimated_punch_power']

        if 'opponent_1_estimated_punch_resistance' in df.columns:
            df_renamed['opponent_1_resistance'] = df['opponent_1_estimated_punch_resistance']
        if 'opponent_2_estimated_punch_resistance' in df.columns:
            df_renamed['opponent_2_resistance'] = df['opponent_2_estimated_punch_resistance']

        if 'opponent_1_ability_to_take_punch' in df.columns:
            df_renamed['opponent_1_ability_to_take_punch'] = df['opponent_1_ability_to_take_punch']
        if 'opponent_2_ability_to_take_punch' in df.columns:
            df_renamed['opponent_2_ability_to_take_punch'] = df['opponent_2_ability_to_take_punch']

        if 'opponent_1.x' in df.columns:
            df_renamed['opponent_1'] = df['opponent_1.x']
        if 'opponent_2.x' in df.columns:
            df_renamed['opponent_2'] = df['opponent_2.x']

        if 'fight_id' in df.columns:
            df_renamed['fight_id'] = df['fight_id']

        # Aggregate round-level data if needed
        if 'round.x' in df_renamed.columns and df_renamed['round.x'].nunique() > 1:
            fight_data = df_renamed.groupby('fight_id').agg({
                'opponent_1': 'first',
                'opponent_2': 'first',
                'opponent_1_power': 'mean',
                'opponent_2_power': 'mean',
                'opponent_1_resistance': 'mean',
                'opponent_2_resistance': 'mean',
                'opponent_1_ability_to_take_punch': 'mean',
                'opponent_2_ability_to_take_punch': 'mean',
                'verdict': 'first'
            }).reset_index()
        else:
            fight_data = df_renamed.copy()

        # Calculate differences
        fight_data['power_diff'] = fight_data['opponent_1_power'] - fight_data['opponent_2_power']
        fight_data['resistance_diff'] = fight_data['opponent_1_resistance'] - fight_data['opponent_2_resistance']
        fight_data['ability_diff'] = fight_data['opponent_1_ability_to_take_punch'] - fight_data['opponent_2_ability_to_take_punch']

        # Extract verdict type
        def extract_verdict_type(verdict):
            if pd.isna(verdict):
                return None
            verdict_str = str(verdict).upper()
            if 'KO' in verdict_str:
                return 'KO'
            elif 'TKO' in verdict_str:
                return 'TKO'
            elif 'UD' in verdict_str:
                return 'UD'
            elif 'SD' in verdict_str:
                return 'SD'
            elif 'MD' in verdict_str:
                return 'MD'
            elif 'RTD' in verdict_str:
                return 'RTD'
            return None

        fight_data['verdict_type'] = fight_data['verdict'].apply(extract_verdict_type)
        fight_data = fight_data.dropna(subset=['verdict_type'])

        if len(fight_data) == 0:
            return None, None, None, None, None, None, None, None, None, None, None, "No valid verdict types found"

        # Prepare features and target
        features = ['power_diff', 'resistance_diff', 'ability_diff']
        X = fight_data[features].values
        y = fight_data['verdict_type'].values
        X = X.astype(np.float32)

        # Train-test split
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=test_size, random_state=42, stratify=y
        )

        # Standardize
        scaler = StandardScaler()
        X_train_scaled = scaler.fit_transform(X_train)
        X_test_scaled = scaler.transform(X_test)

        # Train SVM
        model = SVC(kernel='rbf', C=10, gamma='scale', probability=True, random_state=123)
        model.fit(X_train_scaled, y_train)

        # Evaluate
        train_accuracy = accuracy_score(y_train, model.predict(X_train_scaled))
        test_accuracy = accuracy_score(y_test, model.predict(X_test_scaled))

        # Cross-validation
        cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
        pipeline = make_pipeline(StandardScaler(), SVC(kernel='rbf', C=10, gamma='scale', random_state=123))
        cv_scores = cross_val_score(pipeline, X, y, cv=cv, scoring='accuracy')
        cv_mean = cv_scores.mean()
        cv_std = cv_scores.std()

        # Retrain on full data
        X_full_scaled = scaler.transform(X)
        model.fit(X_full_scaled, y)
        final_predictions = model.predict(X_full_scaled)

        # Create results dataframe
        results_df = fight_data[['fight_id', 'opponent_1', 'opponent_2', 'verdict_type']].copy()
        results_df.columns = ['fight_id', 'opponent_1', 'opponent_2', 'actual_verdict']
        results_df['svm_prediction'] = final_predictions
        results_df['agreement'] = results_df['actual_verdict'] == results_df['svm_prediction']

        # Confusion matrix
        cm = confusion_matrix(y, final_predictions)
        fig_cm = px.imshow(
            cm, x=model.classes_, y=model.classes_, text_auto=True,
            title="Confusion Matrix", labels=dict(x="Predicted", y="Actual"),
            color_continuous_scale='Blues'
        )
        fig_cm.update_layout(height=500)

        # PCA visualization
        pca = PCA(n_components=2)
        pca_result = pca.fit_transform(X_full_scaled)
        pca_df = pd.DataFrame(pca_result, columns=['PC1', 'PC2'])
        pca_df['verdict'] = y
        color_map = {'KO': '#2E8B57', 'TKO': '#4169E1', 'UD': '#DC143C',
                     'SD': '#FF8C00', 'MD': '#9370DB', 'RTD': '#FF69B4'}
        fig_pca = px.scatter(
            pca_df, x='PC1', y='PC2', color='verdict',
            title="PCA Visualization",
            labels={'PC1': f'PC1 ({pca.explained_variance_ratio_[0]:.1%})',
                   'PC2': f'PC2 ({pca.explained_variance_ratio_[1]:.1%})'},
            color_discrete_map=color_map
        )
        fig_pca.update_layout(height=500)

        # Feature distributions
        feature_data = fight_data[['verdict_type', 'power_diff', 'resistance_diff', 'ability_diff']]
        feature_melted = feature_data.melt(id_vars=['verdict_type'], var_name='Feature', value_name='Difference')
        fig_box = px.box(
            feature_melted, x='verdict_type', y='Difference', color='verdict_type',
            facet_col='Feature', title="Feature Distributions by Verdict Type"
        )
        fig_box.update_layout(height=500)

        # Status message
        class_counts = pd.Series(y).value_counts()
        status = f"### ✅ Training Complete!\n\n"
        status += f"**Total fights:** {len(fight_data)}\n"
        status += f"**Test Accuracy:** {test_accuracy:.1%} (on {len(X_test)} unseen fights)\n"
        status += f"**Cross-Validation:** {cv_mean:.1%} ± {cv_std:.1%}\n"
        status += f"**Train Accuracy (ref):** {train_accuracy:.1%}\n\n"
        status += "**Class Distribution:**\n"
        for verdict, count in class_counts.items():
            status += f"- {verdict}: {count} fights ({count/len(y)*100:.1f}%)\n"

        return (model, scaler, fight_data, results_df, fig_cm, fig_pca, fig_box,
                test_accuracy, cv_mean, cv_std, train_accuracy, status)

    except Exception as e:
        import traceback
        return None, None, None, None, None, None, None, None, None, None, None, f"Error: {str(e)}"

# ============================================================================
# PREDICTION FUNCTION
# ============================================================================

def predict_fight(model, scaler, power_diff, resistance_diff, ability_diff):
    """Predict verdict for a new fight"""
    if model is None:
        return None, None, None

    input_features = np.array([[power_diff, resistance_diff, ability_diff]])
    input_scaled = scaler.transform(input_features)

    prediction = model.predict(input_scaled)[0]
    probabilities = model.predict_proba(input_scaled)[0]
    confidence = max(probabilities)

    color_map = {'KO': '#2E8B57', 'TKO': '#4169E1', 'UD': '#DC143C',
                 'SD': '#FF8C00', 'MD': '#9370DB', 'RTD': '#FF69B4'}

    prob_df = pd.DataFrame({'Verdict': model.classes_, 'Probability': probabilities})
    fig = px.bar(
        prob_df, x='Verdict', y='Probability',
        title=f"Prediction: {prediction} (Confidence: {confidence:.1%})",
        color='Verdict', color_discrete_map=color_map,
        text=prob_df['Probability'].apply(lambda x: f'{x:.1%}')
    )
    fig.update_traces(textposition='outside')
    fig.update_layout(yaxis_tickformat='.0%', height=400)

    return prediction, confidence, fig

# ============================================================================
# MAIN APP UI
# ============================================================================

# Sidebar
with st.sidebar:
    st.header("📁 Data Upload")
    uploaded_file = st.file_uploader("Upload your merged CSV file", type=['csv'])

    test_size = st.slider(
        "Test Set Proportion", min_value=0.1, max_value=0.3, value=0.2, step=0.05,
        help="Portion of data held out for final evaluation (20% recommended)"
    )

    if uploaded_file is not None:
        if st.button("🚀 Train Model", type="primary"):
            with st.spinner("Training SVM model with validation..."):
                df = pd.read_csv(uploaded_file)
                result = train_model_with_validation(df, test_size=test_size)

                if result is None or result[-1] is None:
                    st.error("Training failed")
                elif "Error" in str(result[-1]):
                    st.error(result[-1])
                else:
                    (model, scaler, fight_data, results_df, fig_cm, fig_pca, fig_box,
                     test_accuracy, cv_mean, cv_std, train_accuracy, status) = result

                    st.session_state.model = model
                    st.session_state.scaler = scaler
                    st.session_state.fight_data = fight_data
                    st.session_state.results_df = results_df
                    st.session_state.fig_cm = fig_cm
                    st.session_state.fig_pca = fig_pca
                    st.session_state.fig_box = fig_box
                    st.session_state.test_accuracy = test_accuracy
                    st.session_state.cv_mean = cv_mean
                    st.session_state.cv_std = cv_std
                    st.session_state.train_accuracy = train_accuracy
                    st.session_state.status = status
                    st.session_state.trained = True

                    st.success(f"✅ Model trained! Test accuracy: {test_accuracy:.1%}")

# Main content
if st.session_state.get('trained', False):
    # Display status
    st.markdown(st.session_state.status)

    # Metrics row
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Total Fights", len(st.session_state.fight_data))
    with col2:
        st.metric("Test Accuracy", f"{st.session_state.test_accuracy:.1%}")
    with col3:
        st.metric("CV Accuracy", f"{st.session_state.cv_mean:.1%} ± {st.session_state.cv_std:.1%}")
    with col4:
        st.metric("Support Vectors", len(st.session_state.model.support_))

    # Tabs
    tab1, tab2, tab3, tab4 = st.tabs(["📊 Results", "📈 Performance", "🔬 Analysis", "🔮 Predict"])

    with tab1:
        st.subheader("Prediction Results")
        st.dataframe(st.session_state.results_df, use_container_width=True)

        col1, col2 = st.columns(2)
        with col1:
            st.subheader("Class Distribution")
            class_dist = st.session_state.fight_data['verdict_type'].value_counts()
            st.bar_chart(class_dist)
        with col2:
            st.subheader("Agreement Rate")
            agreement = st.session_state.results_df.groupby('actual_verdict')['agreement'].mean()
            st.bar_chart(agreement)

    with tab2:
        st.subheader("Confusion Matrix")
        st.plotly_chart(st.session_state.fig_cm, use_container_width=True)

        st.subheader("Classification Report")
        report = classification_report(
            st.session_state.fight_data['verdict_type'],
            st.session_state.results_df['svm_prediction'],
            output_dict=True
        )
        report_df = pd.DataFrame(report).transpose()
        st.dataframe(report_df)

    with tab3:
        st.subheader("PCA Visualization")
        st.plotly_chart(st.session_state.fig_pca, use_container_width=True)

        st.subheader("Feature Distributions")
        st.plotly_chart(st.session_state.fig_box, use_container_width=True)

    with tab4:
        col1, col2 = st.columns(2)
        with col1:
            power = st.slider("Power Difference (F1 - F2)", -50, 50, 0, 5)
            resistance = st.slider("Resistance Difference (F1 - F2)", -50, 50, 0, 5)
            ability = st.slider("Ability Difference (F1 - F2)", -50, 50, 0, 5)
            if st.button("Predict Verdict"):
                pred, conf, fig = predict_fight(
                    st.session_state.model, st.session_state.scaler,
                    power, resistance, ability
                )
                with col2:
                    if conf > 0.7:
                        st.success(f"### 🥊 {pred}\nConfidence: {conf:.1%} (HIGH)")
                    elif conf > 0.55:
                        st.warning(f"### 🥊 {pred}\nConfidence: {conf:.1%} (MODERATE)")
                    else:
                        st.error(f"### 🥊 {pred}\nConfidence: {conf:.1%} (LOW)")
                    st.plotly_chart(fig, use_container_width=True)

else:
    st.info("👈 Please upload your CSV file in the sidebar and click 'Train Model' to begin")

    st.markdown("""
    ### How to Use This Tool

    1. **Upload your merged CSV file** using the sidebar
    2. **Click "Train Model"** - the model will automatically:
       - Split data into training and test sets
       - Perform 5-fold cross-validation
       - Report TRUE generalization performance
    3. **Explore the results** in the tabs
    """)